# Generated by Django 3.2.3 on 2024-10-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество продуктов'),
        ),
    ]
